name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy-via-ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: 'Deployment'
        
    - name: install ssh keys
      uses: appleboy/ssh-action@master
      env:
        CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
        IMAGE_NAME: ${{ vars.IMAGE_NAME }}
       
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: |
          CONTAINER_NAME, IMAGE_NAME, DOCKER_HUB_USERNAME
        script: |
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true
          docker pull $DOCKER_HUB_USERNAME/$IMAGE_NAME:latest
          docker run -d \
            --name $CONTAINER_NAME \
            -p $12345:$12345 \
            $DOCKER_HUB_USERNAME/$IMAGE_NAME:latest
